### ISSUE TITLE
vMix VT playback integration

### ISSUE THREAD

**Issue by canoemoose** [Alteka/VTKounter#10]
- [ ] vMix connected -> Shows connected
- [ ] VT playing -> Time counts down
- [ ] VT paused -> Time pauses but remains displayed (?)
- [ ] More than 1 VT playing -> Output is something sane
- [ ] VT stopped -> "No VT" or custom configured text
- [ ] VT skipped through -> Time jumps appropriately
- [ ] vMix closed -> Shows disconnected
- [ ] Only correctly filtered cues are tracked (?)

**Comment by garethnunns** [comment]
I believe #12 supports all of these:

- [x] vMix connected -> Shows connected
    **Yes - shows connected on first successful response from vMix**
- [x]  VT playing -> Time counts down
    **Yes**
- [x]  VT paused -> Time pauses but remains displayed (?)
    **Yes and time remains**
- [ ]  More than 1 VT playing -> Output is something sane
    **As the filtering is currently limited to one input (or the main output) then this is the case**
- [x]  VT stopped -> "No VT" or custom configured text
    **Yes**
- [x]  VT skipped through -> Time jumps appropriately
    Yes
- [ ]  vMix closed -> Shows disconnected
     This will get caught by the timeout
- [ ]  Only correctly filtered cues are tracked (?)
    **Currently, all that is filtered is the input number, however this could easily be expanded to the GUID & input name (like Companion allows). Further expansion would be allowing filtering by type of and perhaps a comma delimited list of inputs?**

Would appreciate others testing to confirm the above.

**Comment by DrewLX** [comment]
I have tested the above, so closing this issue. Thanks for your work GN!
