### ISSUE TITLE
vMix text/timer integration like OBS

### ISSUE THREAD

**Issue by canoemoose** [Alteka/VTKounter#11]

**Comment by DrewLX** [comment]
I actually see this is only so worthwhile if we have a browser output. Almost to the point that the OBS web socket feed is only so useful?!

**Comment by garethnunns** [comment]
[vMix supports JSON](https://www.vmix.com/help24/index.htm?DataSources.html), which might be a useful for other applications too; this could be part of the web server support (#3)

**Comment by DrewLX** [comment]
How does vMix poll the json data source? I can't see in the UI / documentation any settings for this. Otherwise adding the feature isn't that hard, but not sure how useful it is.

**Comment by DrewLX** [comment]
Done on latest master commit

**Comment by garethnunns** [comment]
[This video](https://youtu.be/t9CcKd9GeSY) covers how they are polled and [the manual](https://www.vmix.com/help24/index.htm?DataSources.html) mentions it's expected as an array, which isn't the most common way to return an API and looks like a few other people have had [issues](https://forums.vmix.com/posts/t11852-JSON-datasource--Autowrapping-content-when-necessary).

Maybe there could be a couple of endpoints, e.g.

### http://localhost:12345/api/v1/all
````json
{
  "data": {
    "app": {
      "name": "QLab",
      "longName": "",
      "ip": "127.0.0.1",
      "connected": true
    },
    "timer": {
      "text": "04:05:06",
      "hours": 4,
      "minutes": 5,
      "seconds": 6,
      "ms": 0,
      "playing": true
    }
  }
}
````

### http://localhost:12345/api/v1/all/array
The same data as above but as an array

````json
[
  "QLab",
  "",
  "127.0.0.1",
  true,
  "04:05:06",
  4,
  5,
  6,
  0,
  true
]
````

**Comment by DrewLX** [comment]
I'll test with vMix tomorrow and amend as needed

**Comment by garethnunns** [comment]
I have just tested this and it does not appear to work, will have an experiment now!

**Comment by DrewLX** [comment]
Ok, I can also do some testing over the next couple of days. I'm keen to
drop an update release within a few weeks of this and 1.2 of Kards.

Drew Perry

*___________*
07737 206091
<http://www.amplifyvideo.co.uk/>www.drewperry.co.uk

**Comment by DrewLX** [comment]
I'm happy this is updated to a good level, with sensible built in documentation etc. When we're ready to release I'll update the website articles on how to use and maybe do a video guide on how to use with vMix.
