### ISSUE TITLE
Feature Request: Audio announcements

### ISSUE THREAD

**Issue by garethnunns** [Alteka/VTKounter#13]
On some shows it would be great to have automated count-outs on VTs, this could be similar to the audio feature in [Kards](https://github.com/Alteka/Kards). 

Some potential options for this:

- Announce the VT name at start
- How often to annouce - 1 minute, 30 seconds, 10 to 1, etc.
- Voice - system voices, @canoemoose, etc.
- Language
- Interface to output via

**Comment by DrewLX** [comment]
Yeah, I had much the same thoughts, would be really nice to feed into a comms ring etc. 

I think it should be a free form list of announcements, you can set the times and words for each one. Therefore just use the system speech as per Kards and no need for localisation. 

Maybe with the option of a beep at the end of the voice, which marks the timer accurately?

**Comment by DrewLX** [comment]
The basics of this has been implemented and will be in release 0.9
