### ISSUE TITLE
Feature Request: VLC Support

### ISSUE THREAD

**Issue by mckeetech** [Alteka/VTKounter#18]
I use VLC for the majority of my show media playback - I'd love to see both audio and video countdown timer support from VTKounter.

**Comment by markvesterskov** [comment]
Should be feasible using [https://www.npmjs.com/package/node-vlc-http]. I'll have a look at it in the near future if my current pull request gets merged.

**Comment by DrewLX** [comment]
Mark has added this to his PR which is merged in and will be released in an upcoming release
