### ISSUE TITLE
Add integration for Playback Pro

### ISSUE THREAD

**Issue by DrewLX** [Alteka/VTKounter#5]

**Comment by canoemoose** [comment]
- [ ] PBP+ connected -> Shows connected
- [ ] VT playing -> Time counts down
- [ ] VT paused -> Time pauses but remains displayed
- [ ] More than 1 VT playing -> Output is something sane (?)
- [ ] VT stopped -> "No VT" or custom configured text
- [ ] VT skipped through -> Time jumps appropriately
- [ ] PBP+ closed -> Shows disconnected
- [ ] Only correctly filtered cues are tracked (?)

**Comment by garethnunns** [comment]
I believe #12 adds support for the following:


> * [x]  PBP+ connected -> Shows connected

**Yes**

> * [x]  VT playing -> Time counts down

**Yes**

> * [x]  VT paused -> Time pauses but remains displayed

**Yes**

> * [ ]  More than 1 VT playing -> Output is something sane (?)

**AFAIK, PP+ cannot play more that one VT**

> * [x]  VT stopped -> "No VT" or custom configured text

**Yes**

> * [x]  VT skipped through -> Time jumps appropriately

**Yes**

> * [x]  PBP+ closed -> Shows disconnected

**Yes, caught by timeout**

> * [ ]  Only correctly filtered cues are tracked (?)

**This is not currently implemented - I think for most usage of PP+ this would suffice, also [the API](https://www.dtvideolabs.com/user-guide-playbackproplus/#6.2) doesn't provide too much information**

**Comment by DrewLX** [comment]
I'm happy with this level of support, and I've tested the same.
