### ISSUE TITLE
Add integration for ProVideoPlayer

### ISSUE THREAD

**Issue by DrewLX** [Alteka/VTKounter#6]

**Comment by canoemoose** [comment]
- [ ] PVP connected -> Shows connected
- [ ] VT playing -> Time counts down
- [ ] VT paused -> Time pauses but remains displayed
- [ ] More than 1 VT playing -> Output is something sane
- [ ] VT stopped -> "No VT" or custom configured text
- [ ] VT skipped through -> Time jumps appropriately
- [ ] PVP closed -> Shows disconnected
- [ ] Only correctly filtered cues are tracked (?)
