### ISSUE TITLE
Test QLab for correct event handling

### ISSUE THREAD

**Issue by canoemoose** [Alteka/VTKounter#8]
- [ ] VT QLab connected -> Shows connected
- [ ] VT playing -> Time counts down
- [ ] VT paused -> Time pauses but remains displayed
- [ ] More than 1 VT playing -> Output is something sane
- [ ] VT stopped -> "No VT" or custom configured text
- [ ] VT skipped through -> Time jumps appropriately
- [ ] VT QLab closed -> Shows disconnected
- [ ] Only correctly filtered cues are tracked

**Comment by DrewLX** [comment]
I have a 'known only in my head' bug that QLab cues that are paused are NOT correctly tracked.

**Comment by DrewLX** [comment]
Current Status
> * [x]  VT QLab connected -> Shows connected
> * [x]  VT playing -> Time counts down
> * [ ]  VT paused -> Time pauses but remains displayed
> * [x]  More than 1 VT playing -> Output is something sane 
_It reports the first matching cue_
> * [x]  VT stopped -> "No VT" or custom configured text
> * [x]  VT skipped through -> Time jumps appropriately
> * [x]  VT QLab closed -> Shows disconnected
> * [x]  Only correctly filtered cues are tracked

**Comment by DrewLX** [comment]
Fixed paused VTs and tested all other features in QLab.
